### ISSUE TITLE
the pre-trained model for Davis and Kiba data

### ISSUE THREAD

**Issue by afwefrre** [chao1224/GraphMVP#10]
Hi,

Thanks for the great work! I tried to fine-tune the shared pre-trained model to make more predictions. 
But I'm a beginner on the positive side.There are some places that I don't understand clearly,so i have some questions.
I would like to finetune the model on Davis and Kiba data, but I do not know which  pre-trained model in Google drive is suitable for dti_finetune.py --input_model_file.

Thank you very much.

**Comment by chao1224** [comment]
Hi @afwefrre 
Thank you for your interest in our work.
The model weights in the google drive I uploaded now are only for classification tasks (to sync with the previous SSL research line). I will clean up the pretrained models for regression tasks (including Davis and Kiba) and upload them ASAP.

**Comment by zhaoyanpeng208** [comment]
Thank you for your excellent work! I would also like to use your pre-training for regression tasks such like lipo. Looking forward to your model!

**Comment by chao1224** [comment]
Hi @afwefrre @zhaoyanpeng208 
I have uploaded a version [here](https://drive.google.com/file/d/1D6WQoG44P6aaypG0vHThk-xFeW8FdMZx/view?usp=sharing)
