### ISSUE TITLE
Can I get the Source code for pre-training

### ISSUE THREAD

**Issue by twintail520** [chao1224/GraphMVP#11]
Thank you for your excellent work! I would also like to use your pre-training for regression tasks such as Davis and Kiba.

**Comment by chao1224** [comment]
Hi @twintail520 
The source code has been provided in the git repo.
For the checkpoints on regression tasks, I have them uploaded [here](https://drive.google.com/file/d/1D6WQoG44P6aaypG0vHThk-xFeW8FdMZx/view?usp=sharing).
