### ISSUE TITLE
question on the presence of hydrogen atom between pretraining phase and finetuning phase

### ISSUE THREAD

**Issue by koalaaaaaaaaa** [chao1224/GraphMVP#14]
Thank you so much for your code, it's clearly written! : ) 
With respect to your data preprocessing scheme, I have a small question to ask, hope that you'll help me with it when you're free.
_I notice that (if I didn't get things wrong), during pretraining, the 2D and 3D molecules both contain hydrogen atoms, while during finetuning, 2D molecules don't contain hydrogen atoms._
I'm wondering why the pretrained model works great in downstream tasks considering the gap caused by the presence of hydrogen atoms. And I'm curious about whether you've tried to use 2D molecules with hydrogen atoms in downstream tasks, or use 2D and 3D molecules without hydrogen atoms during pretraining?
Thanks a lot for your kindest reply.

**Comment by chao1224** [comment]
Hi @koalaaaaaaaaa, thank you for the question.

Can you help point out where the corresponding codes are?

**Comment by koalaaaaaaaaa** [comment]
thanks for your reply!
1. **During pretraining, 2D and 3D molecules contain hydrogen atoms**. It can be concluded with the following code. (in `src_regression/GEOM_dataset_preparation.py`, line 211)

![image](https://user-images.githubusercontent.com/59307253/233980526-1aa44580-2bad-4119-902b-e60f9771f05c.png)
To be specific, the last line of the code transfer **rdkit_mol** to graph, and it can be seen from the other codes that **rdkit_mol** is the mol **with** hydrogen atoms, so the inputs during pretraining are molecules with hydrogens.

2. **During finetuning, 2D molecules do not contain hydrogen atoms.** It can be concluded with the following code. (`in src_classification/datasets/molecule_datasets.py`, line 672)
![image](https://user-images.githubusercontent.com/59307253/233981895-f0631051-de3d-4e5d-8262-4a7b54225392.png)
To be specific, when loading tox21 datasets (one benchmark from MoleculeNet, other datasets are likewise), the **rdkit_mol** is transferred from SMILEs **without** hydrogen, so the inputs during finetuning is molecules without hydrogens.

I may get things wrong due to my little experience in this area, if so, please kindly point out, thank you a lot!!

**Comment by chao1224** [comment]
Hi @koalaaaaaaaaa,

Thanks for reminding me. So here are some comments:
1. In the current implementation (according to the codes you shared above), we are just parsing the raw data from the input data. This means that:
    - The original GEOM dataset contains H, and we just take it.
    - For downstream tasks, we take `MolFromSmiles` function with default parameters on the input SMILES. Now it seems H is not included in this case.
2. Further on the downstream tasks, I remembered there were a few parameters that I played around with, including `AddHs` and `sanitize`. It turned out that some molecules would become invalid, and the number of data points would change accordingly. Thus, in order to keep **consistent** with the literature at that time, we just follow the existing data preprocessing at that time, like [this repo](https://github.com/snap-stanford/pretrain-gnns/tree/master/chem).
    - Recall that scaffold splitting is used for downstream tasks, so the number of data points could be important to certain extent.
    - This code was written about two years ago, and I don't remember the exact detailed parameters I was testing. But feel free to give it a try.

Hope this helps.

**Comment by koalaaaaaaaaa** [comment]
Thanks for your reply so much！
I still amazed at the great performance this model has achieved, even with the gap (caused by the presence of hydrogen atoms.) between pretraining and downstream tasks.

**Comment by chao1224** [comment]
I'm not sure if this is a gap or richer information. Another way to understand it is:
1. In pretraining, GraphMVP has roughly two components:
    - [Component 1] graph -- (encoding) --> node and edge embedding
    - [Component 2] node and edge embedding -- (representation function) --> representation
2. Now for the downstream:
    - [Component 1] The pretrained encoding on H is not used, but other pretrained encodings are still useful, like the ones on C, N, O.
    - [Component 2] The pretrained representation function is beneficial as it learns the inherent structure.
