### ISSUE TITLE
Documentation on how to encode and decode a molecule

### ISSUE THREAD

**Issue by htalibart** [chao1224/GraphMVP#17]
Hi, thanks for providing your code, your work seems very promising!

However I couldn't find the documentation I was looking for. If I understand correctly, GraphMVP is able to input a molecular graph, encode it into a latent space, and decode this embedding into a molecular graph again. Could you provide the documentation on how to do both of these steps, from latent space and back?

Thank you!

**Comment by chao1224** [comment]
Hi @htalibart,

Thank you for your interest in our work!

## Encoding

- The 2D encoding is [here](https://github.com/chao1224/GraphMVP/blob/main/src_classification/pretrain_GraphMVP.py#L62-L63).
- The 3D encoding is [here](https://github.com/chao1224/GraphMVP/blob/main/src_classification/pretrain_GraphMVP.py#LL66C94-L67C1).

I am working on a benchmark repo, where I will include a notebook as a tutorial. Please stay tuned on this! :)

## Decoding

For the 2D->3D and 3D->2D generation, GraphMVP employs an approximate solution to learn the representation, i.e., variational representation reconstruction (VRR), and no decoding is required in VRR.

However, we do have a follow-up work called **MoleculeSDE**, which does these two encoding steps exactly. The website together with a demo can be found [here](https://chao1224.github.io/MoleculeSDE). I'm still cleaning up the codes for MoleculeSDE, which should be available in one or two weeks.

Hope this answers your question.

**Comment by htalibart** [comment]
Thank you for your answer!
I understand that the decoding is not required for the applications you're interested in, but I would be interested in working in this latent space, for instance if I encode a molecule and slightly modify the resulting embedding would it be possible to decode it and get another (valid) molecule?

**Comment by chao1224** [comment]
Hi @htalibart,

Welcome to play around with the decoding in MoleculeSDE, which shall be available soon. (I'm pushing this)

Meanwhile, the one you mentioned is very interesting, and I personally call this as molecule editing or molecule conditional generation. I have done several works on this (e.g., [GraphCG](https://chao1224.github.io/GraphCG) and [MoleculeSTM](https://chao1224.github.io/MoleculeSTM)), and the answer is positive: changing the latent does change the output decoded molecules. I'm quite optimistic about getting similar observations in MoleculeSDE.

**Comment by htalibart** [comment]
Ok many thanks for your answer and best of luck for your submissions!

**Comment by chao1224** [comment]
Hi @htalibart, the code for MoleculeSDE is released [here](https://github.com/chao1224/MoleculeSDE). Feel free to check.

**Comment by htalibart** [comment]
> Hi @htalibart, the code for MoleculeSDE is released [here](https://github.com/chao1224/MoleculeSDE). Feel free to check.

Many thanks for the follow-up, I will check!
