### ISSUE TITLE
Pre-trained models for regression tasks

### ISSUE THREAD

**Issue by sun-heqi** [chao1224/GraphMVP#19]
In the "GraphMVP_complate_features_for_regression" folder, there are only `graphMVP_C` and `graphMVP_G` pre-trained models. Do you have the original `GraphMVP` pre-trained model for regression tasks?

**Comment by chao1224** [comment]
Hi @sun-heqi,

Sorry for the delay. I just got time to fix this issue.

So I uploaded the checkpoints now. Feel free to check the google drive link.

Now I have checkpoints for three models:
- GraphMVP
- GraphMVP_AM (or GraphMVP_G)
- GraphMVP_CP (or GraphMVP_C)
