### ISSUE TITLE
Request to GraphMVP pre-trained weights

### ISSUE THREAD

**Issue by junxia97** [chao1224/GraphMVP#2]
Hi Shengchao,

Thanks for your great work and clear documentation! I try to download your pre-trained model with the provided link. However, I can't find it. Could you share the pre-trained models with us?

Regards,
Jun.

**Comment by chao1224** [comment]
Hi Jun,

Thank you for your interest in our work. We are still cleaning up the repo and will upload them (including pre-trained model weights and log files) soon.

Regards,
Shengchao

**Comment by chao1224** [comment]
Hi @junxia97 

We just quickly uploaded a noisy version to google drive. Feel free to check it out. More detailed descriptions of this noisy version can be found in #3 .

**Comment by junxia97** [comment]
> Hi @junxia97
> 
> We just quickly uploaded a noisy version to google drive. Feel free to check it out. More detailed descriptions of this noisy version can be found in #3 .
OK. Thanks for your help!
