### ISSUE TITLE
Thank you for your answer!

### ISSUE THREAD

**Issue by HICUELA** [chao1224/GraphMVP#20]
Thank you for your answer!
I understand that the decoding is not required for the applications you're interested in, but I would be interested in working in this latent space, for instance if I encode a molecule and slightly modify the resulting embedding would it be possible to decode it and get another (valid) molecule?

_Originally posted by @htalibart in https://github.com/chao1224/GraphMVP/issues/17#issuecomment-1564815509_

**Comment by chao1224** [comment]
Hi @HICUELA,

We actually tried this in another paper called [GraphCG](https://chao1224.github.io/GraphCG). The answer is yes, though the latent space is on the pretrained HierVAE, not on pretrained GraphMVP.
