### ISSUE TITLE
A problem with replicating code

### ISSUE THREAD

**Issue by clclclaiggg** [chao1224/GraphMVP#22]
Hello, I had this problem when I reproduced your code: 
AttributeError: module 'scipy.stats' has no attribute 'gibrat'.
Does the code have to run on unix systems?

**Comment by chao1224** [comment]
@clclclaiggg This seems to be a package version issue. What is your scipy version?

BTW. We only test the scripts on the UNIX system by far.

**Comment by clclclaiggg** [comment]
the scipy version  is 1.7.3，and what version of scipy are you using? 
Thanks for your help.

**Comment by clclclaiggg** [comment]
the scipy version  is 1.7.3，and what version of scipy are you using?
Thanks for your help.

**Comment by chao1224** [comment]
It's `scipy 1.6.2` on my end.

**Comment by clclclaiggg** [comment]
> It's `scipy 1.6.2` on my end.

Thank you, I still have this error using version 1.6.2,
I'm going to try unix now

**Comment by huohuoxi** [comment]
I tried descriptastorus-2.4.2 and scipy-1.6.2, and the problem may disappear. Maybe you can change your descriptastorus version either.
