### ISSUE TITLE
Why the classification task and the regression task have different model checkpoint?

### ISSUE THREAD

**Issue by StefanIsSmart** [chao1224/GraphMVP#25]
And what is the relationship with GraphMVP, GraphMVP-G, GraphMVP-C?

**Comment by StefanIsSmart** [comment]
By the way, maybe the `ogb` version has been updated.

`	size mismatch for atom_encoder.atom_embedding_list.1.weight: copying a param with shape torch.Size([4, 300]) from checkpoint, the shape in current model is torch.Size([5, 300]).
`

The dimension of the pre-trained model is not correct

**Comment by chao1224** [comment]
Hi,

- These are two variants: C for contrastive and G for generative. You can check Eq 8 in the [paper](https://openreview.net/forum?id=xQUe1pOKPam).
- Yes, the checkpoints are using the older version of OGB. You can also check #23
