### ISSUE TITLE
I cannot use other gnn models in your code

### ISSUE THREAD

**Issue by nickspark** [chao1224/GraphMVP#6]
when I set 
gnn_type = 'graphsage'
to use graphsage instead of gin, I got the following errors, do you have any idea about it?
`MessagePassing.propagate` only supports `torch.LongTensor` of shape `[2, num_messages]` or `torch_sparse.SparseTensor` for argument `edge_index`.

**Comment by chao1224** [comment]
Hi @nickspark , our current implementation is using GIN only.
For the GraphSAGE, we followed [this repo](https://github.com/snap-stanford/pretrain-gnns).
Yet, I will check this and get back to you soon.

**Comment by chao1224** [comment]
Hi @nickspark ,
I updated the GNN with the latest pyg version. Feel free to check out.
