### ISSUE TITLE
The model type of pretrained weights?

### ISSUE THREAD

**Issue by josiehong** [chao1224/GraphMVP#8]
Hi, 

Thanks for the great work! I tried to fine-tune the shared pre-trained model to make more predictions. There are three models in Google drive, and I just want to check the model types. In my understanding: 

- `GraphMVP/GEOM_3D_nmol50000_nconf5_nupper1000/CL_1_VAE_1/6_51_10_0.1/0.15_EBM_dot_prod_0.2_normalize_l2_detach_target_2_100_0` is GraphMVP. 
- `GraphMVP_hybrid/GEOM_3D_nmol50000_nconf5_nupper1000/CL_1_VAE_1_AM_1/6_51_10_0.1/0.15_EBM_dot_prod_0.05_normalize_l2_detach_target_2_100_0` is GraphMVP-G. 
- `GraphMVP_hybrid/GEOM_3D_nmol50000_nconf5_nupper1000/CL_1_VAE_1_CP_0.1/6_51_10_0.1/0.15_EBM_dot_prod_0.2_normalize_l2_detach_target_2_100_0` is GraphMVP-C. 

Do I understand it correctly? Thanks!

Josie

**Comment by chao1224** [comment]
Hi Josie @JosieHong ,

Thank you for your interest in our work.
And yes, your understanding is correct.

Shengchao
