### ISSUE TITLE
MoleculeProteinModel and ProteinModel classes are not founded

### ISSUE THREAD

**Issue by solanoon** [chao1224/GraphMVP#9]
Hello,

I would like to finetune the model on Davis and Kiba data, but it seems that the **MoleculeProteinModel** and **ProteinModel** classes are not defined and could not be imported.

Could you please check the codes necessary for the drug-target affinity tasks?

Thank you very much.

**Comment by chao1224** [comment]
Hi @solanoon, sorry that I deleted it by mistake while cleaning the repo. I just added it back and cleaned up the dataset README accordingly. Feel free to check out.
